### ISSUE TITLE
Error: Direct-connected device does not generate the network

### ISSUE THREAD

**Issue by huuhuannt1998** [SmartThingsCommunity/st-device-sdk-c#138]
I am testing out the Direct-connected device. However, when I tried to connect to the device using Smartthings app, it asked to join a custom network but it was unable to join. How can I fix this?

![image_123650291 (1)](https://github.com/SmartThingsCommunity/st-device-sdk-c/assets/47999808/c24e0d88-5db6-4287-a0a7-21bf590e35cf)
![image_123650291](https://github.com/SmartThingsCommunity/st-device-sdk-c/assets/47999808/c7d98e93-fbec-4abe-8387-fd8cd84163ab)

**Comment by junyoun-kim** [comment]
@huuhuannt1998 Sorry for late response.

Could you share device's log and SmartThings app version?

Also could you check if you can see same wifi ssid name(Switch Demo_E40BLe0016HedO1UTw) in wifi scan list in phone setting?

**Comment by junyoun-kim** [comment]
Hello, @huuhuannt1998   Is there any more questions? We will close this issue if no more updates.
