### ISSUE TITLE
Feature Request/Suggestion: iot-core as an ESP IDF component

### ISSUE THREAD

**Issue by momo1** [SmartThingsCommunity/st-device-sdk-c#59]
Hi,

iot-core CMakeLists.txt can detect if the user is using ESP IDF and then takes a slightly different approach to make iot-core an IDF component instead of a shared lib to link against. I understand that this CMakeLists file is meant to be generic so that the lib can be linked to any port. It probably would complicate your CMake file by a little bit but simplifies ours :smiley:  and makes the project better adhere to the ESP IDF pattern.

Thanks

**Comment by Kwang-Hui** [comment]
Hi. thanks for your suggestion.
We will put your suggestion into our future consideration list.
