### ISSUE TITLE
Please provide Arduino-based development

### ISSUE THREAD

**Issue by alvaromi** [SmartThingsCommunity/st-device-sdk-c#6]
Many IoT hobbyists and developers use Arduino-based development, which already provides very well-established cross-platform abstraction layers for Arduino, ESP*, STM*, Raspberry PI, etc, etc, etc... Why not provide a SmartThings library support for Arduino-based development? This would tremendously help those who will need to port their classic implementations in the near future, as well as anyone who will want to create new integrations!

**Comment by Kwang-Hui** [comment]
Thanks for your opinion.
We are working on expanding SmartThings Devices SDK's porting layer by referring market demands.
We supports FreeRTOS, TizenRT for real devices now and have many others are under developing.
We may support Arduino-base development eventually but it takes long time for now.
If you are really interested in Arduino porting, we are always welcome to your contribution.
