### ISSUE TITLE
Example app needs to be updated

### ISSUE THREAD

**Issue by toddaustin07** [SmartThingsCommunity/st-device-sdk-c#75]
Example app uses several deprecated functions/macros which need to be updated.  Building the current app results in several deprecation warnings.

**Comment by stdk-scm** [comment]
Hi @toddaustin07 ,

Thanks for the report.
I'll check.

Thanks.
Kwang-Hui Cho

**Comment by Kwang-Hui** [comment]
example src has been updated https://github.com/SmartThingsCommunity/st-device-sdk-c/commit/da561aac9bbc990ce1992b236c65cf674dae603d#diff-50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c

Thanks.
